Backup/Eurovision/Areas/Mobile/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Eurovision.Models;
using System.Web.Profile;
using System.Web.Security;

namespace Eurovision.Areas.Mobile.Controllers
{
    [Authorize]
    public class GameController : Controller
    {
        SourceRepository db = new SQLRepository();
        public GameController()
            : this(new SQLRepository())
        { }
        public GameController(SourceRepository repository)
        {
            db = repository;
        }

        public ActionResult Join(int id)
        {
            EventPlayer model = new EventPlayer { Year = id };
            model.PlayerGuid = (Guid)Membership.GetUser().ProviderUserKey;

            int? previousScore = db.GetUserPredictionForYear(id, model.PlayerGuid);
            if (previousScore != null && previousScore > 0)
            {
                model.PredictedUKScore = previousScore;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Join(EventPlayer model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model.Event = db.GetEventByYear(model.Year);
                    db.AddEventPlayer(model);
                    HttpContext.Profile.SetPropertyValue("CurrentGame", model.Year);
                    var CountryList = db.GetEventCountriesByYear(model.Year);
                    ICollection<PlayerEventCountryScore> PECS = new List<PlayerEventCountryScore>();
                    foreach (var item in CountryList)
                    {
                        PECS.Add(new PlayerEventCountryScore
                        {
                            EventCountryID = item.CountryID,
                            PlayerGuid = model.PlayerGuid,
                            EventCountry = item
                        });
                    }
                    db.StartGameForPlayer(PECS);
                    return RedirectToAction("Play", "Game");
                }
                else
                {
                    throw new Exception("Modelstate invalid");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error", ex.InnerException);
                return View(model);
            }
        }
        public ActionResult Play()
        {
            Guid guid = (Guid)Membership.GetUser().ProviderUserKey;
            GameVM model = new GameVM();
            model.Event = db.GetEventByYear((int)HttpContext.Profile.GetPropertyValue("CurrentGame"));
            model.EventPlayer = db.GetCurrentEventPlayer(model.Event.Year, guid);
            model.PlayerScores = db.GetPlayerScoresForYear(model.Event.Year, guid);
            return View(model);
        }
        public ActionResult Score(int id)
        {
            PlayerEventCountryScore model = db.GetPlayerScoreByID(id);
            Guid currentplayer = (Guid)Membership.GetUser().ProviderUserKey;
            if (currentplayer != model.PlayerGuid)
            {
                throw new Exception("You are not the correct player for this record");
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult Score(PlayerEventCountryScore model)
        {
            //check validity of user
            Guid currentplayer = (Guid)Membership.GetUser().ProviderUserKey;
            if (currentplayer != model.PlayerGuid)
            {
                //invalid user -- throw error 
                throw new Exception("You are not the correct player for this record");
            }
            //check validity of model
            try
            {
                if (ModelState.IsValid)
                {
                    db.RecordPlayerScore(model);
                    return RedirectToAction("Play");
                }
                else
                {
                    throw new Exception("Modelstate.invalid");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error", ex);
                model.EventCountry = db.GetEventCountry(model.EventCountryID);
                return View(model);
            }
        }
    }
}

Backup/Eurovision/Controllers/CheckMyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Eurovision.Models;

namespace Eurovision.Controllers
{
    public class CheckMyController : Controller
    {
        SourceRepository db = new SQLRepository();
        public CheckMyController()
            : this(new SQLRepository())
        { }
        public CheckMyController(SourceRepository repository)
        {
            db = repository;
        }


        public ActionResult Fattest(int id)
        {
            PlayerEventCountryScore pecs = db.GetPlayerScoreByID(id);

            //get current user
            Guid playerID = pecs.PlayerGuid;

            //get any fattest scores==true 
            var FatScores = db.GetPlayerScoresForYear(pecs.EventCountry.Event.Year, playerID).Where(x => x.Fattest == true);
            if (FatScores.Count() > 0)
            {
                return Json(new { success = true, matches = FatScores.Select(x => x.EventCountry.Country.Name) }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
        }

    }
}

Backup/Eurovision/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Eurovision.Models;
using System.Web.Profile;
using System.Web.Security;

namespace Eurovision.Controllers
{
    [Authorize]
    public class GameController : Controller
    {
        SourceRepository db = new SQLRepository();
        public GameController()
            : this(new SQLRepository())
        { }
        public GameController(SourceRepository repository)
        {
            db = repository;
        }

        public ActionResult Join(int id)
        {
            EventPlayer model = new EventPlayer { Year = id };
            model.PlayerGuid = (Guid)Membership.GetUser().ProviderUserKey;

            int? previousScore = db.GetUserPredictionForYear(id, model.PlayerGuid);
            if (previousScore!=null && previousScore>0)
            {
                model.PredictedUKScore = previousScore;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Join(EventPlayer model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model.Event = db.GetEventByYear(model.Year);
                    db.AddEventPlayer(model);
                    HttpContext.Profile.SetPropertyValue("CurrentGame", model.Year);
                    var CountryList = db.GetEventCountriesByYear(model.Year);
                    ICollection<PlayerEventCountryScore> PECS = new List<PlayerEventCountryScore>();
                    foreach (var item in CountryList)
                    {
                        PECS.Add(new PlayerEventCountryScore
                        {
                            EventCountryID = item.CountryID,
                            PlayerGuid = model.PlayerGuid,
                            EventCountry = item
                        });
                    }
                    db.StartGameForPlayer(PECS);
                    return RedirectToAction("Play", "Game");
                }
                else
                {
                    throw new Exception("Modelstate invalid");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error", ex.InnerException);
                return View(model);
            }
        }
        public ActionResult Play()
        {
            Guid guid = (Guid)Membership.GetUser().ProviderUserKey;
            GameVM model = new GameVM();
            model.Event = db.GetEventByYear((int)HttpContext.Profile.GetPropertyValue("CurrentGame"));
            model.EventPlayer = db.GetCurrentEventPlayer(model.Event.Year, guid);
            model.PlayerScores = db.GetPlayerScoresForYear(model.Event.Year, guid);
            return View(model);
        }
        public ActionResult Score(int id)
        {
            PlayerEventCountryScore model = db.GetPlayerScoreByID(id);
            Guid currentplayer = (Guid)Membership.GetUser().ProviderUserKey;
            if (currentplayer != model.PlayerGuid)
            {
                throw new Exception("You are not the correct player for this record");
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult Score(PlayerEventCountryScore model)
        {
            //check validity of user
            Guid currentplayer = (Guid)Membership.GetUser().ProviderUserKey;
            if (currentplayer != model.PlayerGuid)
            {
                //invalid user -- throw error 
                throw new Exception("You are not the correct player for this record");
            }
            //check validity of model
            try
            {
                if (ModelState.IsValid)
                {
                    db.RecordPlayerScore(model);
                    return RedirectToAction("Play");
                }
                else
                {
                    throw new Exception("Modelstate.invalid");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error",ex);
                model.EventCountry = db.GetEventCountry(model.EventCountryID);
                return View(model);
            }
        }
    }
}

Backup/Eurovision/Controllers/MyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Eurovision.Models;
using System.Web.Profile;

namespace Eurovision.Controllers
{
    
    public class MyController : Controller
    {
        public ActionResult Profile()
        {
            ProfileBase currentProfile = HttpContext.Profile;
            ProfileVM model = new ProfileVM();
            model.DisplayName = currentProfile.GetPropertyValue("DisplayName").ToString();
            model.CurrentGame = (int)currentProfile.GetPropertyValue("CurrentGame");
            return View(model);
        }
        [HttpPost]
        public ActionResult Profile(ProfileVM model)
        {
            ProfileBase current =  HttpContext.Profile;
            if (current.GetPropertyValue("DisplayName") != model.DisplayName)
            {
                current.SetPropertyValue("DisplayName", model.DisplayName);
            }
            if ((int)current.GetPropertyValue("CurrentGame") != model.CurrentGame)
            {
                current.SetPropertyValue("CurrentGame", model.CurrentGame);
            }
            return View(model);
        }
        public ActionResult SwapShowNotes()
        {
            bool curVal = (bool)HttpContext.Profile.GetPropertyValue("ShowNotes");
            HttpContext.Profile.SetPropertyValue("ShowNotes", !curVal);
            return Json(new { newVal = !curVal }, JsonRequestBehavior.AllowGet);
        }
    }
}

Backup/Eurovision/Areas/Mobile/Views/Game/Join.cshtml
@model Eurovision.Models.EventPlayer

@{
    ViewBag.Title = string.Format("Join {0} game", Model.Year);
}
@using (Html.BeginForm("Join", "Game", FormMethod.Post, new { @class = "form", autocomplete="off" }))
{
    <ul>   
    @if (Model.PredictedUKScore > 0)
    {
        <li class="legend">Sorry, @HttpContext.Current.Profile.GetPropertyValue("DisplayName")</li>
        <li>
            You previously guessed @Model.PredictedUKScore for this years competition.  Please contact your administrator to change it!
        </li>
        <li id="send"><a href="@Url.Action("Play")" style="text-decoration:none;"><input type="button" value="Go" style="text-decoration:none;"/></a></li>
    }
    else
    {
        <li class="legend">Okay, @HttpContext.Current.Profile.GetPropertyValue("DisplayName") you want to play in @Model.Year?</li>
        <li>Enter your UK score prediction and hit go...</li>
        <li>
            @Html.LabelFor(m => m.PredictedUKScore)    
            @Html.TextBoxFor(m => m.PredictedUKScore, new { type = "number", pattern = "\\d*", style = "width:50px;" })
        </li>
        @Html.HiddenFor(m => m.PlayerGuid)
        @Html.HiddenFor(m => m.Year)
        <li id="send"><input type="submit" value = "Go"/></li>
    }
    </ul>
}
@Html.SetFocus(m => m.PredictedUKScore)

Backup/Eurovision/Areas/Mobile/Views/Game/Play.cshtml
@model Eurovision.Models.GameVM
@{
    ViewBag.Title = string.Format("Play {0}",Model.Event.Year);
}
@section head{
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <style type="text/css">
    ul 
    {
        list-style-type: none;
        margin: 0px;
        border-left:0px;
        padding-left:0px;
    }
    li.country:nth-child(odd) { background: #eeeeee; }
    li.country
    {
        /*height:32px;*/
        min-height:32px;
        width:100%;
        clear:both;
    }
    li.country a
    {
        display: block;
        text-decoration:none;
    }
    li.country a:hover
    {
        background-color:#cccccc;
    }
    li.country img
    {
        vertical-align:middle;
        padding:4px;
    }
    .score
    {
        float:right;
        width:32px;
        line-height:32px;
        vertical-align:middle;
        text-align:center;
        padding:4px;
    }
    .angled
    {
        -webkit-transform: rotate(-45deg);
        -moz-transform: rotate(-45deg);
        -o-transform: rotate(-45deg);
        -ms-transform: rotate(-45deg);
        transform: rotate(-45deg);
    }
@@media screen and (orientation:portrait) {
    .player { display: none; }
}

@@media screen and (orientation:landscape) {
        .player { display: inline; }
}
    </style>
    <script type="text/javascript">
        function ShowNotes(val) {
            if (val == "False" || val == false) {
                $(".notes").show();
                $("#showHideNotes").html("Hide notes");
            } else {
                $(".notes").hide();
                $("#showHideNotes").html("Show notes");
            }
        };

        $(document).ready(function () {
            //onload show hide the notes from the settings
            ShowNotes('@HttpContext.Current.Profile.GetPropertyValue("ShowNotes")');

            $("#showHideNotes").click(function () {
                $.ajax({
                    url: '@Url.Action("SwapShowNotes","My")',
                    type: "post",
                    success: function (result) {
                        ShowNotes(result.newVal);
                    }
                });
            });
        });
    </script>
}
<h6 style="margin:0">@ViewBag.Title - Scored @Model.PlayerScores.Where(a=>a.Score!=null).Count()/@Model.PlayerScores.Count()<span id="showHideNotes" style="float:right;">Hide notes</span></h6>
@if (Model != null && Model.PlayerScores.Count() > 0)
{
    <div class="country" style="vertical-align:bottom;">
        Country
        <span class="score angled">Score</span>
        <span class="score angled">Fattest</span>
        <span class="score angled">Bongos</span>
    </div>
    <ul>
    @foreach (var item in Model.PlayerScores)
    {
        <li class="country">
            <a href="@Url.Action("Score", new { id = item.id })">
                @{
                    string img = "~/Content/Images/{0} lrg{1}.png";
                    string bw = "";
                    if (item.Score == null)
                    {
                        bw = " bw";
                    }
                    img = string.Format(img, item.EventCountry.Country.image, bw);
                }
                <img src="@Url.Content(img)" alt="@item.EventCountry.Country.Name flag"/>
                <span>@item.EventCountry.Country.Name <span class="player">- <img src="@Url.Content("~/Content/Images/player.png")" alt="player" />@item.EventCountry.CountryOwnedBy</span> @if (item.Score == null)
                                                                                                                                                                { <text> - Click to record score</text> }</span>
                <span class="score">@item.Score</span>
                <span class="score">@if (item.Fattest) { <img alt="fattest" src="@Url.Content("~/Content/Images/player.png")" /> }</span>
                <span class="score">@if (item.BestUseOfBongos){ <img alt="Bongos" src="@Url.Content("~/Content/Images/music.png")" /> }</span>
            </a>
            <div style="display:block;clear:both;" class="notes">@item.Notes</div>
        </li> 
    }
    </ul>
}

Backup/Eurovision/Areas/Mobile/Views/Game/Score.cshtml
@model Eurovision.Models.PlayerEventCountryScore
@{
    ViewBag.Title = string.Format("Enter score for {0}", Model.EventCountry.Country.Name);
}
@section head{
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.11.min.js")" type="text/javascript"></script>
    <link href="@Url.Content("~/Content/jquery-ui-1.10.3.custom.min.css")" rel="stylesheet" type="text/css" />
    <script type="text/javascript">
        $(document).ready(function () {

            $(".check-box").click(function () {
                if ($(this).is(':checked')) {
                    var cType = $(this).data("test");
                    var url = '@Url.Action("ActionAction", "CheckMy", new { id = "xx" })'
                                .replace('ActionAction', cType)
                                .replace('xx', $(this).data("id"));
                    var ctrl = $(this);
                    $.ajax({
                        url: url,
                        type: "post",
                        success: function (result) {
                            if (result.success) {
                                //prompt to remove existing matches and only replace if user clicks yes
                                $("#cType").text(cType);
                                $("#cExist").text(result.matches[0]);
                                //$("#dialog-form").dialog("open");
                                $("#dialog-form").dialog({
                                    modal: true,
                                    dialogClass: "noclose",
                                    title: "Replace " + cType + "?",
                                    buttons: {
                                        "Yes": function () {
                                            //clear the checkbox
                                            $(this).dialog("close");
                                        },
                                        "No": function () {
                                            ctrl.attr('checked', false);
                                            $(this).dialog("close");
                                        }
                                    }
                                });
                            }
                        }
                    });
                }
            });
        });
    </script>
    <style type="text/css">
    .noclose .ui-dialog-titlebar-close
    {
        display:none;
    }
    </style>
}
@using (Html.BeginForm("Score", "Game", FormMethod.Post, new { @class = "form", autocomplete = "off" }))
{
    <ul>
        <li class="legend"><h6>@ViewBag.Title</h6></li>
        <li>
            @Html.LabelFor(m => m.Score)
            @Html.TextBoxFor(m => m.Score, new { type = "number", pattern = "\\d*", style = "width:50px;" })
            @Html.ValidationMessageFor(m => m.Score)
        </li>
        <li>
            @Html.LabelFor(m => m.BestUseOfBongos)
            @Html.CheckBoxFor(m => m.BestUseOfBongos, new { data_test = "Bongos", data_id = Model.id, @class = "check-box" })
        </li>
        <li>
            @Html.LabelFor(m => m.Fattest)
            @Html.CheckBoxFor(m => m.Fattest, new { data_test = "Fattest", data_id = Model.id, @class = "check-box" })
        </li>
        <li>
            @Html.LabelFor(m => m.Notes)
            @Html.EditorFor(m => m.Notes)
        </li>
        <li id="send">
            @Html.HiddenFor(m => m.EventCountryID) 
            @Html.HiddenFor(m => m.PlayerGuid) 
            @Html.HiddenFor(m => m.id) 
            <input type="submit" value="Submit" />
        </li>
    </ul>
}
@Html.SetFocus(m => m.Score)

<div id="dialog-form" style="display:none;">
  <div>Really?! @Model.EventCountry.Country.Name is the <span id="cType">&nbsp;</span>, not <span id="cExist">&nbsp;</span>?</div>
</div>